#数据源 account
sharding:
  jdbc:
    datasource:
      names: account
      account:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/p4_account?useUnicode=true&characterEncoding=UTF-8&serberTimezone=GMT%2B8
        username: root
        password: 1234
        #水平拆分的数据库表配置分库+分表策略
        config:
          sharding:
            #分库策略
#          default-database-strategy:
#            inline:
#              sharding-column: id
#              algorithe-expression: p4-account
      #分表策略
      tables:
        p4_account:
          actual-data-nodes: p4-account.p4_account_info_$->{0..15}
          table-strategy:
            inline:
              sharding-column: id
              #分片算法表达式
              algorithm-exprission: p4_account_info_$->{id % 2}

        #打印执行的数据库
        props:
          sql:
            show: true
        #打印执行的sql语句
        spring:
          main:
            allow-bean-definition-overriding: true
